/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module attEffectRom_16 (
    input [7:0] address,
    output reg [4:0] eff
  );
  
  
  
  always @* begin
    eff = 5'h00;
    
    case (address)
      1'h0: begin
        eff = 5'h00;
      end
      1'h1: begin
        eff = 5'h00;
      end
      2'h2: begin
        eff = 5'h1f;
      end
      2'h3: begin
        eff = 5'h01;
      end
      3'h4: begin
        eff = 5'h00;
      end
      3'h5: begin
        eff = 5'h1f;
      end
      3'h6: begin
        eff = 5'h01;
      end
      3'h7: begin
        eff = 5'h00;
      end
      4'h8: begin
        eff = 5'h01;
      end
      4'h9: begin
        eff = 5'h01;
      end
      4'ha: begin
        eff = 5'h1f;
      end
      4'hb: begin
        eff = 5'h01;
      end
      4'hc: begin
        eff = 5'h00;
      end
      4'hd: begin
        eff = 5'h1f;
      end
      4'he: begin
        eff = 5'h01;
      end
      4'hf: begin
        eff = 5'h00;
      end
      5'h10: begin
        eff = 5'h00;
      end
      5'h11: begin
        eff = 5'h01;
      end
      5'h12: begin
        eff = 5'h01;
      end
      5'h13: begin
        eff = 5'h00;
      end
      5'h14: begin
        eff = 5'h00;
      end
      5'h15: begin
        eff = 5'h00;
      end
      5'h16: begin
        eff = 5'h00;
      end
      5'h17: begin
        eff = 5'h01;
      end
      5'h18: begin
        eff = 5'h01;
      end
      5'h19: begin
        eff = 5'h1f;
      end
      5'h1a: begin
        eff = 5'h01;
      end
      5'h1b: begin
        eff = 5'h00;
      end
      5'h1c: begin
        eff = 5'h00;
      end
      5'h1d: begin
        eff = 5'h01;
      end
      5'h1e: begin
        eff = 5'h1f;
      end
      5'h1f: begin
        eff = 5'h00;
      end
      6'h20: begin
        eff = 5'h00;
      end
      6'h21: begin
        eff = 5'h1f;
      end
      6'h22: begin
        eff = 5'h01;
      end
      6'h23: begin
        eff = 5'h00;
      end
      6'h24: begin
        eff = 5'h00;
      end
      6'h25: begin
        eff = 5'h01;
      end
      6'h26: begin
        eff = 5'h1f;
      end
      6'h27: begin
        eff = 5'h00;
      end
      6'h28: begin
        eff = 5'h01;
      end
      6'h29: begin
        eff = 5'h1f;
      end
      6'h2a: begin
        eff = 5'h00;
      end
      6'h2b: begin
        eff = 5'h00;
      end
      6'h2c: begin
        eff = 5'h00;
      end
      6'h2d: begin
        eff = 5'h01;
      end
      6'h2e: begin
        eff = 5'h00;
      end
      6'h2f: begin
        eff = 5'h01;
      end
      6'h30: begin
        eff = 5'h00;
      end
      6'h31: begin
        eff = 5'h1f;
      end
      6'h32: begin
        eff = 5'h00;
      end
      6'h33: begin
        eff = 5'h1f;
      end
      6'h34: begin
        eff = 5'h00;
      end
      6'h35: begin
        eff = 5'h01;
      end
      6'h36: begin
        eff = 5'h00;
      end
      6'h37: begin
        eff = 5'h01;
      end
      6'h38: begin
        eff = 5'h00;
      end
      6'h39: begin
        eff = 5'h01;
      end
      6'h3a: begin
        eff = 5'h00;
      end
      6'h3b: begin
        eff = 5'h1f;
      end
      6'h3c: begin
        eff = 5'h00;
      end
      6'h3d: begin
        eff = 5'h1f;
      end
      6'h3e: begin
        eff = 5'h00;
      end
      6'h3f: begin
        eff = 5'h01;
      end
      7'h40: begin
        eff = 5'h00;
      end
      7'h41: begin
        eff = 5'h1f;
      end
      7'h42: begin
        eff = 5'h00;
      end
      7'h43: begin
        eff = 5'h1f;
      end
      7'h44: begin
        eff = 5'h00;
      end
      7'h45: begin
        eff = 5'h01;
      end
      7'h46: begin
        eff = 5'h00;
      end
      7'h47: begin
        eff = 5'h01;
      end
      7'h48: begin
        eff = 5'h01;
      end
      7'h49: begin
        eff = 5'h01;
      end
      7'h4a: begin
        eff = 5'h00;
      end
      7'h4b: begin
        eff = 5'h1f;
      end
      7'h4c: begin
        eff = 5'h00;
      end
      7'h4d: begin
        eff = 5'h1f;
      end
      7'h4e: begin
        eff = 5'h00;
      end
      7'h4f: begin
        eff = 5'h01;
      end
      7'h50: begin
        eff = 5'h00;
      end
      7'h51: begin
        eff = 5'h1f;
      end
      7'h52: begin
        eff = 5'h00;
      end
      7'h53: begin
        eff = 5'h00;
      end
      7'h54: begin
        eff = 5'h01;
      end
      7'h55: begin
        eff = 5'h01;
      end
      7'h56: begin
        eff = 5'h00;
      end
      7'h57: begin
        eff = 5'h00;
      end
      7'h58: begin
        eff = 5'h1f;
      end
      7'h59: begin
        eff = 5'h1f;
      end
      7'h5a: begin
        eff = 5'h00;
      end
      7'h5b: begin
        eff = 5'h00;
      end
      7'h5c: begin
        eff = 5'h01;
      end
      7'h5d: begin
        eff = 5'h01;
      end
      7'h5e: begin
        eff = 5'h00;
      end
      7'h5f: begin
        eff = 5'h00;
      end
      7'h60: begin
        eff = 5'h1f;
      end
      7'h61: begin
        eff = 5'h01;
      end
      7'h62: begin
        eff = 5'h00;
      end
      7'h63: begin
        eff = 5'h00;
      end
      7'h64: begin
        eff = 5'h1f;
      end
      7'h65: begin
        eff = 5'h1f;
      end
      7'h66: begin
        eff = 5'h00;
      end
      7'h67: begin
        eff = 5'h00;
      end
      7'h68: begin
        eff = 5'h01;
      end
      7'h69: begin
        eff = 5'h1f;
      end
      7'h6a: begin
        eff = 5'h00;
      end
      7'h6b: begin
        eff = 5'h01;
      end
      7'h6c: begin
        eff = 5'h00;
      end
      7'h6d: begin
        eff = 5'h01;
      end
      7'h6e: begin
        eff = 5'h00;
      end
      7'h6f: begin
        eff = 5'h1f;
      end
      7'h70: begin
        eff = 5'h1f;
      end
      7'h71: begin
        eff = 5'h00;
      end
      7'h72: begin
        eff = 5'h1f;
      end
      7'h73: begin
        eff = 5'h01;
      end
      7'h74: begin
        eff = 5'h00;
      end
      7'h75: begin
        eff = 5'h00;
      end
      7'h76: begin
        eff = 5'h01;
      end
      7'h77: begin
        eff = 5'h1f;
      end
      7'h78: begin
        eff = 5'h00;
      end
      7'h79: begin
        eff = 5'h01;
      end
      7'h7a: begin
        eff = 5'h1f;
      end
      7'h7b: begin
        eff = 5'h00;
      end
      7'h7c: begin
        eff = 5'h00;
      end
      7'h7d: begin
        eff = 5'h00;
      end
      7'h7e: begin
        eff = 5'h01;
      end
      7'h7f: begin
        eff = 5'h1f;
      end
      8'h80: begin
        eff = 5'h00;
      end
      8'h81: begin
        eff = 5'h00;
      end
      8'h82: begin
        eff = 5'h00;
      end
      8'h83: begin
        eff = 5'h1f;
      end
      8'h84: begin
        eff = 5'h00;
      end
      8'h85: begin
        eff = 5'h00;
      end
      8'h86: begin
        eff = 5'h1f;
      end
      8'h87: begin
        eff = 5'h1f;
      end
      8'h88: begin
        eff = 5'h00;
      end
      8'h89: begin
        eff = 5'h00;
      end
      8'h8a: begin
        eff = 5'h01;
      end
      8'h8b: begin
        eff = 5'h1f;
      end
      8'h8c: begin
        eff = 5'h00;
      end
      8'h8d: begin
        eff = 5'h00;
      end
      8'h8e: begin
        eff = 5'h1f;
      end
      8'h8f: begin
        eff = 5'h01;
      end
      8'h90: begin
        eff = 5'h00;
      end
      8'h91: begin
        eff = 5'h00;
      end
      8'h92: begin
        eff = 5'h00;
      end
      8'h93: begin
        eff = 5'h1f;
      end
      8'h94: begin
        eff = 5'h00;
      end
      8'h95: begin
        eff = 5'h00;
      end
      8'h96: begin
        eff = 5'h1f;
      end
      8'h97: begin
        eff = 5'h00;
      end
      8'h98: begin
        eff = 5'h00;
      end
      8'h99: begin
        eff = 5'h00;
      end
      8'h9a: begin
        eff = 5'h00;
      end
      8'h9b: begin
        eff = 5'h00;
      end
      8'h9c: begin
        eff = 5'h00;
      end
      8'h9d: begin
        eff = 5'h00;
      end
      8'h9e: begin
        eff = 5'h01;
      end
      8'h9f: begin
        eff = 5'h00;
      end
      8'ha0: begin
        eff = 5'h1f;
      end
      8'ha1: begin
        eff = 5'h00;
      end
      8'ha2: begin
        eff = 5'h1f;
      end
      8'ha3: begin
        eff = 5'h00;
      end
      8'ha4: begin
        eff = 5'h00;
      end
      8'ha5: begin
        eff = 5'h00;
      end
      8'ha6: begin
        eff = 5'h1f;
      end
      8'ha7: begin
        eff = 5'h00;
      end
      8'ha8: begin
        eff = 5'h1f;
      end
      8'ha9: begin
        eff = 5'h00;
      end
      8'haa: begin
        eff = 5'h1f;
      end
      8'hab: begin
        eff = 5'h00;
      end
      8'hac: begin
        eff = 5'h01;
      end
      8'had: begin
        eff = 5'h00;
      end
      8'hae: begin
        eff = 5'h01;
      end
      8'haf: begin
        eff = 5'h00;
      end
      8'hb0: begin
        eff = 5'h1f;
      end
      8'hb1: begin
        eff = 5'h00;
      end
      8'hb2: begin
        eff = 5'h00;
      end
      8'hb3: begin
        eff = 5'h00;
      end
      8'hb4: begin
        eff = 5'h01;
      end
      8'hb5: begin
        eff = 5'h00;
      end
      8'hb6: begin
        eff = 5'h01;
      end
      8'hb7: begin
        eff = 5'h00;
      end
      8'hb8: begin
        eff = 5'h1f;
      end
      8'hb9: begin
        eff = 5'h00;
      end
      8'hba: begin
        eff = 5'h01;
      end
      8'hbb: begin
        eff = 5'h00;
      end
      8'hbc: begin
        eff = 5'h00;
      end
      8'hbd: begin
        eff = 5'h00;
      end
      8'hbe: begin
        eff = 5'h1f;
      end
      8'hbf: begin
        eff = 5'h00;
      end
      8'hc0: begin
        eff = 5'h01;
      end
      8'hc1: begin
        eff = 5'h00;
      end
      8'hc2: begin
        eff = 5'h00;
      end
      8'hc3: begin
        eff = 5'h1f;
      end
      8'hc4: begin
        eff = 5'h1f;
      end
      8'hc5: begin
        eff = 5'h00;
      end
      8'hc6: begin
        eff = 5'h00;
      end
      8'hc7: begin
        eff = 5'h01;
      end
      8'hc8: begin
        eff = 5'h1f;
      end
      8'hc9: begin
        eff = 5'h00;
      end
      8'hca: begin
        eff = 5'h00;
      end
      8'hcb: begin
        eff = 5'h1f;
      end
      8'hcc: begin
        eff = 5'h01;
      end
      8'hcd: begin
        eff = 5'h00;
      end
      8'hce: begin
        eff = 5'h00;
      end
      8'hcf: begin
        eff = 5'h01;
      end
      8'hd0: begin
        eff = 5'h1f;
      end
      8'hd1: begin
        eff = 5'h00;
      end
      8'hd2: begin
        eff = 5'h00;
      end
      8'hd3: begin
        eff = 5'h1f;
      end
      8'hd4: begin
        eff = 5'h01;
      end
      8'hd5: begin
        eff = 5'h00;
      end
      8'hd6: begin
        eff = 5'h00;
      end
      8'hd7: begin
        eff = 5'h01;
      end
      8'hd8: begin
        eff = 5'h1f;
      end
      8'hd9: begin
        eff = 5'h00;
      end
      8'hda: begin
        eff = 5'h00;
      end
      8'hdb: begin
        eff = 5'h1f;
      end
      8'hdc: begin
        eff = 5'h01;
      end
      8'hdd: begin
        eff = 5'h00;
      end
      8'hde: begin
        eff = 5'h00;
      end
      8'hdf: begin
        eff = 5'h01;
      end
      8'he0: begin
        eff = 5'h1f;
      end
      8'he1: begin
        eff = 5'h00;
      end
      8'he2: begin
        eff = 5'h00;
      end
      8'he3: begin
        eff = 5'h00;
      end
      8'he4: begin
        eff = 5'h1f;
      end
      8'he5: begin
        eff = 5'h00;
      end
      8'he6: begin
        eff = 5'h00;
      end
      8'he7: begin
        eff = 5'h1f;
      end
      8'he8: begin
        eff = 5'h01;
      end
      8'he9: begin
        eff = 5'h1f;
      end
      8'hea: begin
        eff = 5'h00;
      end
      8'heb: begin
        eff = 5'h00;
      end
      8'hec: begin
        eff = 5'h00;
      end
      8'hed: begin
        eff = 5'h01;
      end
      8'hee: begin
        eff = 5'h00;
      end
      8'hef: begin
        eff = 5'h00;
      end
      8'hf0: begin
        eff = 5'h00;
      end
      8'hf1: begin
        eff = 5'h01;
      end
      8'hf2: begin
        eff = 5'h00;
      end
      8'hf3: begin
        eff = 5'h00;
      end
      8'hf4: begin
        eff = 5'h00;
      end
      8'hf5: begin
        eff = 5'h1f;
      end
      8'hf6: begin
        eff = 5'h00;
      end
      8'hf7: begin
        eff = 5'h01;
      end
      8'hf8: begin
        eff = 5'h01;
      end
      8'hf9: begin
        eff = 5'h00;
      end
      8'hfa: begin
        eff = 5'h1f;
      end
      8'hfb: begin
        eff = 5'h00;
      end
      8'hfc: begin
        eff = 5'h00;
      end
      8'hfd: begin
        eff = 5'h00;
      end
      8'hfe: begin
        eff = 5'h01;
      end
      8'hff: begin
        eff = 5'h00;
      end
      9'h100: begin
        eff = 5'h00;
      end
      9'h101: begin
        eff = 5'h00;
      end
      9'h102: begin
        eff = 5'h01;
      end
      9'h103: begin
        eff = 5'h00;
      end
      9'h104: begin
        eff = 5'h00;
      end
      9'h105: begin
        eff = 5'h00;
      end
      9'h106: begin
        eff = 5'h1f;
      end
      9'h107: begin
        eff = 5'h00;
      end
      9'h108: begin
        eff = 5'h00;
      end
      9'h109: begin
        eff = 5'h00;
      end
      9'h10a: begin
        eff = 5'h00;
      end
      9'h10b: begin
        eff = 5'h1f;
      end
      9'h10c: begin
        eff = 5'h00;
      end
      9'h10d: begin
        eff = 5'h00;
      end
      9'h10e: begin
        eff = 5'h00;
      end
      9'h10f: begin
        eff = 5'h01;
      end
      9'h110: begin
        eff = 5'h01;
      end
      9'h111: begin
        eff = 5'h00;
      end
      9'h112: begin
        eff = 5'h00;
      end
      9'h113: begin
        eff = 5'h00;
      end
      9'h114: begin
        eff = 5'h1f;
      end
      9'h115: begin
        eff = 5'h01;
      end
      9'h116: begin
        eff = 5'h00;
      end
      9'h117: begin
        eff = 5'h1f;
      end
      9'h118: begin
        eff = 5'h00;
      end
      9'h119: begin
        eff = 5'h00;
      end
      9'h11a: begin
        eff = 5'h00;
      end
      9'h11b: begin
        eff = 5'h01;
      end
      9'h11c: begin
        eff = 5'h00;
      end
      9'h11d: begin
        eff = 5'h00;
      end
      9'h11e: begin
        eff = 5'h00;
      end
      9'h11f: begin
        eff = 5'h00;
      end
      9'h120: begin
        eff = 5'h1f;
      end
      9'h121: begin
        eff = 5'h00;
      end
      9'h122: begin
        eff = 5'h00;
      end
      9'h123: begin
        eff = 5'h01;
      end
      9'h124: begin
        eff = 5'h01;
      end
      9'h125: begin
        eff = 5'h00;
      end
      9'h126: begin
        eff = 5'h00;
      end
      9'h127: begin
        eff = 5'h1f;
      end
      9'h128: begin
        eff = 5'h1f;
      end
      9'h129: begin
        eff = 5'h1f;
      end
      9'h12a: begin
        eff = 5'h00;
      end
      9'h12b: begin
        eff = 5'h00;
      end
      9'h12c: begin
        eff = 5'h00;
      end
      9'h12d: begin
        eff = 5'h1f;
      end
      9'h12e: begin
        eff = 5'h00;
      end
      9'h12f: begin
        eff = 5'h00;
      end
      9'h130: begin
        eff = 5'h00;
      end
      9'h131: begin
        eff = 5'h00;
      end
      9'h132: begin
        eff = 5'h00;
      end
      9'h133: begin
        eff = 5'h01;
      end
      9'h134: begin
        eff = 5'h00;
      end
      9'h135: begin
        eff = 5'h00;
      end
      9'h136: begin
        eff = 5'h00;
      end
      9'h137: begin
        eff = 5'h01;
      end
      9'h138: begin
        eff = 5'h00;
      end
      9'h139: begin
        eff = 5'h01;
      end
      9'h13a: begin
        eff = 5'h00;
      end
      9'h13b: begin
        eff = 5'h1f;
      end
      9'h13c: begin
        eff = 5'h01;
      end
      9'h13d: begin
        eff = 5'h01;
      end
      9'h13e: begin
        eff = 5'h00;
      end
      9'h13f: begin
        eff = 5'h1f;
      end
      9'h140: begin
        eff = 5'h01;
      end
      9'h141: begin
        eff = 5'h00;
      end
      9'h142: begin
        eff = 5'h00;
      end
      9'h143: begin
        eff = 5'h00;
      end
      9'h144: begin
        eff = 5'h1f;
      end
      9'h145: begin
        eff = 5'h00;
      end
      9'h146: begin
        eff = 5'h00;
      end
      9'h147: begin
        eff = 5'h00;
      end
      9'h148: begin
        eff = 5'h1f;
      end
      9'h149: begin
        eff = 5'h00;
      end
      9'h14a: begin
        eff = 5'h1f;
      end
      9'h14b: begin
        eff = 5'h1f;
      end
      9'h14c: begin
        eff = 5'h00;
      end
      9'h14d: begin
        eff = 5'h00;
      end
      9'h14e: begin
        eff = 5'h1f;
      end
      9'h14f: begin
        eff = 5'h1f;
      end
      9'h150: begin
        eff = 5'h00;
      end
      9'h151: begin
        eff = 5'h00;
      end
      9'h152: begin
        eff = 5'h01;
      end
      9'h153: begin
        eff = 5'h01;
      end
      9'h154: begin
        eff = 5'h1f;
      end
      9'h155: begin
        eff = 5'h00;
      end
      9'h156: begin
        eff = 5'h1f;
      end
      9'h157: begin
        eff = 5'h1f;
      end
      9'h158: begin
        eff = 5'h01;
      end
      9'h159: begin
        eff = 5'h1f;
      end
      9'h15a: begin
        eff = 5'h01;
      end
      9'h15b: begin
        eff = 5'h1f;
      end
      9'h15c: begin
        eff = 5'h1f;
      end
      9'h15d: begin
        eff = 5'h01;
      end
      9'h15e: begin
        eff = 5'h01;
      end
      9'h15f: begin
        eff = 5'h01;
      end
      9'h160: begin
        eff = 5'h1f;
      end
      9'h161: begin
        eff = 5'h1f;
      end
      9'h162: begin
        eff = 5'h00;
      end
      9'h163: begin
        eff = 5'h00;
      end
      9'h164: begin
        eff = 5'h1f;
      end
      9'h165: begin
        eff = 5'h1f;
      end
      9'h166: begin
        eff = 5'h00;
      end
      9'h167: begin
        eff = 5'h1f;
      end
      9'h168: begin
        eff = 5'h00;
      end
      9'h169: begin
        eff = 5'h00;
      end
      9'h16a: begin
        eff = 5'h01;
      end
      9'h16b: begin
        eff = 5'h00;
      end
      9'h16c: begin
        eff = 5'h1f;
      end
      9'h16d: begin
        eff = 5'h00;
      end
      9'h16e: begin
        eff = 5'h00;
      end
      9'h16f: begin
        eff = 5'h1f;
      end
      9'h170: begin
        eff = 5'h01;
      end
      9'h171: begin
        eff = 5'h1f;
      end
      9'h172: begin
        eff = 5'h1f;
      end
      9'h173: begin
        eff = 5'h1f;
      end
      9'h174: begin
        eff = 5'h1f;
      end
      9'h175: begin
        eff = 5'h1f;
      end
      9'h176: begin
        eff = 5'h01;
      end
      9'h177: begin
        eff = 5'h1f;
      end
      9'h178: begin
        eff = 5'h1f;
      end
      9'h179: begin
        eff = 5'h00;
      end
      9'h17a: begin
        eff = 5'h00;
      end
      9'h17b: begin
        eff = 5'h00;
      end
      9'h17c: begin
        eff = 5'h00;
      end
      9'h17d: begin
        eff = 5'h00;
      end
      9'h17e: begin
        eff = 5'h00;
      end
      9'h17f: begin
        eff = 5'h00;
      end
      9'h180: begin
        eff = 5'h00;
      end
      9'h181: begin
        eff = 5'h00;
      end
      9'h182: begin
        eff = 5'h00;
      end
      9'h183: begin
        eff = 5'h00;
      end
      9'h184: begin
        eff = 5'h00;
      end
      9'h185: begin
        eff = 5'h00;
      end
      9'h186: begin
        eff = 5'h00;
      end
      9'h187: begin
        eff = 5'h00;
      end
      9'h188: begin
        eff = 5'h00;
      end
      9'h189: begin
        eff = 5'h00;
      end
      9'h18a: begin
        eff = 5'h00;
      end
      9'h18b: begin
        eff = 5'h00;
      end
      9'h18c: begin
        eff = 5'h00;
      end
      9'h18d: begin
        eff = 5'h00;
      end
      9'h18e: begin
        eff = 5'h00;
      end
      9'h18f: begin
        eff = 5'h00;
      end
      9'h190: begin
        eff = 5'h00;
      end
    endcase
  end
endmodule
