/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module instRom_15 (
    input [7:0] address,
    output reg [16:0] inst
  );
  
  
  
  always @* begin
    inst = 17'h00000;
    
    case (address)
      1'h0: begin
        inst = 17'h03e3f;
      end
      1'h1: begin
        inst = 17'h1a000;
      end
      2'h2: begin
        inst = 17'h11000;
      end
      2'h3: begin
        inst = 17'h10700;
      end
      3'h4: begin
        inst = 17'h03e3e;
      end
      3'h5: begin
        inst = 17'h1a000;
      end
      3'h6: begin
        inst = 17'h11000;
      end
      3'h7: begin
        inst = 17'h10700;
      end
      4'h8: begin
        inst = 17'h0670b;
      end
      4'h9: begin
        inst = 17'h1f000;
      end
      4'ha: begin
        inst = 17'h06f0f;
      end
      4'hb: begin
        inst = 17'h01000;
      end
      4'hf: begin
        inst = 17'h03c04;
      end
      5'h10: begin
        inst = 17'h03b04;
      end
      5'h11: begin
        inst = 17'h03a04;
      end
      5'h12: begin
        inst = 17'h03904;
      end
      5'h13: begin
        inst = 17'h1b000;
      end
      5'h14: begin
        inst = 17'h03603;
      end
      5'h15: begin
        inst = 17'h03e3b;
      end
      5'h16: begin
        inst = 17'h1a000;
      end
      5'h17: begin
        inst = 17'h11000;
      end
      5'h18: begin
        inst = 17'h10700;
      end
      5'h19: begin
        inst = 17'h06f32;
      end
      6'h32: begin
        inst = 17'h03d34;
      end
      6'h33: begin
        inst = 17'h06fc8;
      end
      6'h34: begin
        inst = 17'h03132;
      end
      6'h35: begin
        inst = 17'h09110;
      end
      6'h36: begin
        inst = 17'h0713c;
      end
      6'h37: begin
        inst = 17'h03e3d;
      end
      6'h38: begin
        inst = 17'h1a000;
      end
      6'h39: begin
        inst = 17'h11000;
      end
      6'h3a: begin
        inst = 17'h10700;
      end
      6'h3b: begin
        inst = 17'h06fb8;
      end
      6'h3c: begin
        inst = 17'h03800;
      end
      6'h3d: begin
        inst = 17'h06f40;
      end
      7'h40: begin
        inst = 17'h1a000;
      end
      7'h41: begin
        inst = 17'h11000;
      end
      7'h42: begin
        inst = 17'h12700;
      end
      7'h43: begin
        inst = 17'h03d45;
      end
      7'h44: begin
        inst = 17'h06fe1;
      end
      7'h45: begin
        inst = 17'h041fc;
      end
      7'h46: begin
        inst = 17'h07150;
      end
      7'h47: begin
        inst = 17'h03300;
      end
      7'h48: begin
        inst = 17'h05463;
      end
      7'h49: begin
        inst = 17'h0644e;
      end
      7'h4a: begin
        inst = 17'h03301;
      end
      7'h4b: begin
        inst = 17'h08cc3;
      end
      7'h4c: begin
        inst = 17'h03680;
      end
      7'h4d: begin
        inst = 17'h06f50;
      end
      7'h4e: begin
        inst = 17'h0303a;
      end
      7'h4f: begin
        inst = 17'h06fb4;
      end
      7'h50: begin
        inst = 17'h03208;
      end
      7'h51: begin
        inst = 17'h041c2;
      end
      7'h52: begin
        inst = 17'h07155;
      end
      7'h53: begin
        inst = 17'h03039;
      end
      7'h54: begin
        inst = 17'h06fb4;
      end
      7'h55: begin
        inst = 17'h041fb;
      end
      7'h56: begin
        inst = 17'h07160;
      end
      7'h57: begin
        inst = 17'h03301;
      end
      7'h58: begin
        inst = 17'h05463;
      end
      7'h59: begin
        inst = 17'h0645e;
      end
      7'h5a: begin
        inst = 17'h03301;
      end
      7'h5b: begin
        inst = 17'h08bb3;
      end
      7'h5c: begin
        inst = 17'h03680;
      end
      7'h5d: begin
        inst = 17'h06f60;
      end
      7'h5e: begin
        inst = 17'h03038;
      end
      7'h5f: begin
        inst = 17'h06fb4;
      end
      7'h60: begin
        inst = 17'h03208;
      end
      7'h61: begin
        inst = 17'h041b2;
      end
      7'h62: begin
        inst = 17'h07165;
      end
      7'h63: begin
        inst = 17'h03037;
      end
      7'h64: begin
        inst = 17'h06fb4;
      end
      7'h65: begin
        inst = 17'h041fa;
      end
      7'h66: begin
        inst = 17'h07170;
      end
      7'h67: begin
        inst = 17'h03302;
      end
      7'h68: begin
        inst = 17'h05463;
      end
      7'h69: begin
        inst = 17'h0646e;
      end
      7'h6a: begin
        inst = 17'h03301;
      end
      7'h6b: begin
        inst = 17'h08aa3;
      end
      7'h6c: begin
        inst = 17'h03680;
      end
      7'h6d: begin
        inst = 17'h06f70;
      end
      7'h6e: begin
        inst = 17'h03036;
      end
      7'h6f: begin
        inst = 17'h06fb4;
      end
      7'h70: begin
        inst = 17'h03208;
      end
      7'h71: begin
        inst = 17'h041a2;
      end
      7'h72: begin
        inst = 17'h07175;
      end
      7'h73: begin
        inst = 17'h03035;
      end
      7'h74: begin
        inst = 17'h06fb4;
      end
      7'h75: begin
        inst = 17'h041f9;
      end
      7'h76: begin
        inst = 17'h07180;
      end
      7'h77: begin
        inst = 17'h03303;
      end
      7'h78: begin
        inst = 17'h05463;
      end
      7'h79: begin
        inst = 17'h0647e;
      end
      7'h7a: begin
        inst = 17'h03301;
      end
      7'h7b: begin
        inst = 17'h08993;
      end
      7'h7c: begin
        inst = 17'h03680;
      end
      7'h7d: begin
        inst = 17'h06f80;
      end
      7'h7e: begin
        inst = 17'h03034;
      end
      7'h7f: begin
        inst = 17'h06fb4;
      end
      8'h80: begin
        inst = 17'h03208;
      end
      8'h81: begin
        inst = 17'h04192;
      end
      8'h82: begin
        inst = 17'h07196;
      end
      8'h83: begin
        inst = 17'h03033;
      end
      8'h84: begin
        inst = 17'h06fb4;
      end
      8'h96: begin
        inst = 17'h1b000;
      end
      8'h97: begin
        inst = 17'h06f32;
      end
      8'hb4: begin
        inst = 17'h16e00;
      end
      8'hb5: begin
        inst = 17'h1a000;
      end
      8'hb6: begin
        inst = 17'h11000;
      end
      8'hb7: begin
        inst = 17'h10700;
      end
      8'hb8: begin
        inst = 17'h03c00;
      end
      8'hb9: begin
        inst = 17'h03b00;
      end
      8'hba: begin
        inst = 17'h03a00;
      end
      8'hbb: begin
        inst = 17'h03900;
      end
      8'hbc: begin
        inst = 17'h1b000;
      end
      8'hbd: begin
        inst = 17'h03800;
      end
      8'hbe: begin
        inst = 17'h1e000;
      end
      8'hbf: begin
        inst = 17'h06f00;
      end
      8'hc8: begin
        inst = 17'h03400;
      end
      8'hc9: begin
        inst = 17'h03000;
      end
      8'hca: begin
        inst = 17'h03332;
      end
      8'hcb: begin
        inst = 17'h09334;
      end
      8'hcc: begin
        inst = 17'h063d2;
      end
      8'hcd: begin
        inst = 17'h1c140;
      end
      8'hce: begin
        inst = 17'h08010;
      end
      8'hcf: begin
        inst = 17'h03101;
      end
      8'hd0: begin
        inst = 17'h08441;
      end
      8'hd1: begin
        inst = 17'h06fca;
      end
      8'hd2: begin
        inst = 17'h19d00;
      end
      8'he1: begin
        inst = 17'h03501;
      end
      8'he2: begin
        inst = 17'h0c557;
      end
      8'he3: begin
        inst = 17'h03402;
      end
      8'he4: begin
        inst = 17'h0a354;
      end
      8'he5: begin
        inst = 17'h03501;
      end
      8'he6: begin
        inst = 17'h17083;
      end
      8'he7: begin
        inst = 17'h08cc0;
      end
      8'he8: begin
        inst = 17'h18cc0;
      end
      8'he9: begin
        inst = 17'h08335;
      end
      8'hea: begin
        inst = 17'h17083;
      end
      8'heb: begin
        inst = 17'h08bb0;
      end
      8'hec: begin
        inst = 17'h18bb0;
      end
      8'hed: begin
        inst = 17'h08335;
      end
      8'hee: begin
        inst = 17'h17083;
      end
      8'hef: begin
        inst = 17'h08aa0;
      end
      8'hf0: begin
        inst = 17'h18aa0;
      end
      8'hf1: begin
        inst = 17'h08335;
      end
      8'hf2: begin
        inst = 17'h17083;
      end
      8'hf3: begin
        inst = 17'h08990;
      end
      8'hf4: begin
        inst = 17'h18990;
      end
      8'hf5: begin
        inst = 17'h19d00;
      end
    endcase
  end
endmodule
