/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module latch_decoder2_19 (
    input [4:0] in,
    output reg [23:0] out
  );
  
  
  
  always @* begin
    
    case (in)
      1'h0: begin
        out = 24'h040000;
      end
      1'h1: begin
        out = 24'h040000;
      end
      2'h2: begin
        out = 24'h050000;
      end
      2'h3: begin
        out = 24'h058000;
      end
      3'h4: begin
        out = 24'h060000;
      end
      3'h5: begin
        out = 24'h068000;
      end
      default: begin
        out = 24'h040000;
      end
    endcase
  end
endmodule
