/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module statusdecoder_8 (
    output reg [4:0] out,
    input [7:0] in
  );
  
  
  
  always @* begin
    out = 8'h00;
    
    case (in)
      8'h00: begin
        out = 5'h12;
      end
      8'h01: begin
        out = 5'h13;
      end
      8'h02: begin
        out = 5'h14;
      end
      8'h03: begin
        out = 5'h15;
      end
    endcase
  end
endmodule
