/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module question_index_chooser_10 (
    input clk,
    input rst,
    input enable,
    output reg [5:0] out
  );
  
  
  
  wire [32-1:0] M_randgen_num;
  reg [1-1:0] M_randgen_next;
  reg [32-1:0] M_randgen_seed;
  pn_gen_33 randgen (
    .clk(clk),
    .rst(rst),
    .next(M_randgen_next),
    .seed(M_randgen_seed),
    .num(M_randgen_num)
  );
  reg [5:0] M_question_index_d, M_question_index_q = 1'h0;
  
  always @* begin
    M_question_index_d = M_question_index_q;
    
    out[0+5-:6] = M_question_index_q[0+5-:6];
    M_randgen_seed = 11'h4d2;
    M_randgen_next = enable;
    M_question_index_d[0+5-:6] = M_randgen_num[25+4-:5] + M_randgen_num[17+3-:4] + M_randgen_num[10+1-:2];
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_question_index_q <= 1'h0;
    end else begin
      M_question_index_q <= M_question_index_d;
    end
  end
  
endmodule
